
- name: Setup Ha tang Docker
  hosts: all
  become: true
  roles:
    - docker_role

- name: Deploy back end application
  hosts: all
  become: true
  roles:
    - backend_role

- name: common tasks after provisioning
  hosts: all
  become: true
  roles:
    - post_provisioning_role